config/routes.rb
Rails.application.routes.draw do
  get 'sign_up' => 'users#new', :as => "sign_up"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "my_chars" => "users#show", :as => "my_chars"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :users, :characters
  resources :sessions, only: [:new, :create, :destroy]

  root 'pages#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :user
	has_many :char_skills

	validates :char_name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :characters, dependent: :destroy  

  attr_accessor :password

	before_save { self.email = email.downcase }
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create, length: { minimum: 6 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :name,  presence: true, length: { maximum: 50 }
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	def index
		@characters = Character.all
	end

	def show
		@character = Character.find(params[:id])
	end

	def new
		@character = Character.new
	end

	def create
		@character = Character.new(char_params)
	end


	def edit

	end

	def destroy
	end
	
private
	def char_params
		params.require(:character).permit(:user_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:session][:email].downcase, params[:session][:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password."
  		render "new"
  	end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show]

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new", :notice => "My notice"
  end
end



def show
  @user = User.find(params[:id])
end

def edit
    @user = User.find(params[:id])
  end

private
def user_params
	params.require(:user).permit(:name, :email, :password)
end

def set_user
	@user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/index.html.erb
<h1>Characters</h1>

app/views/characters/show.html.erb
<% provide(:title, @character.char_name) %>

<div id="container">
<h2><% @character.char_name %></h2>
sdfsdf
</div>

app/views/layouts/_header.html.erb
<nav class = "navbar navbar-default navbar-default-top navbar-inverse" role="navigation">
	<div class = "container">
		<div class = "navbar-header">
		<ul class="nav navbar-nav navbar-left">
 <li><%= link_to "Space Dice", root_path, id: "logo" %></li>
 <li><%= link_to "Characters", characters_path %></li>
 </ul>
 </div>

<ul class="nav navbar-nav navbar-left">


</ul>


 <ul class="nav navbar-nav navbar-right">
 <% if current_user %>
	 <li class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    		<span class="glyphicon glyphicon-user">&nbsp; </span>   <%= current_user.name %>
    		<span class="caret"></span>

 	 <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1"> <%= link_to "Characters", user_path(current_user) %> </li>
    <li role="presentation"><a role="menuitem" tabindex="-1"><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1"><%= link_to "Sign Out", log_out_path %></a></li>
  </ul>
 	<li></li>
 <% else %>
 	<li><%= link_to "Sign In", log_in_path %></li>
 <% end %>
 </ul>
 </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpaceDice Character Keeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
	<div id = "notice"><% flash[:notice] %> </div>
<% end %>
<%= render "layouts/header" %>
<%= yield %>

      <%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="container">
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
<% @users.each do |user| %>
	<li>
		<%= link_to user.username, user %>
	</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<div class="container">

<div class="row">
<div class="col-md-6 col-md-offset-3">

<div class="text-center">

<%= form_for @user do |f| %>
    <h1>Create New Account</h1>
    <%= link_to "Or log in", log_in_path %>

  <% if @user.errors.any? %>
      <h4>Form is invalid</h4>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :class => "form-control input-lg" %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email, :class => "form-control input-lg" %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password, :class => "form-control input-lg" %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, :class => "form-control input-lg" %>
  </p>
  <%= submit_tag "Create Account", class: "btn btn-primary btn-block btn-lg" %>
<% end %>
</div>

app/views/users/show.html.erb


<h3>Characters</h3>
<ul>
	<% @user.characters.each do |character| %>
	<li><%= link_to character.char_name, character %>	</li>
	<% end %>
</ul>